name: gifencoder
version: 0.1.2
author: Brian Slesinsky <brian-web@slesinsky.org>
description: A library for creating gif files, including animated gifs.
homepage: https://github.com/google/dart-gif-encoder
dev_dependencies:
  browser: any
  unittest: any
